name: Terraform Apply - OCI VCN

on:
  push:
    paths:
      - '**.tf'
      - '**.tfvars'

jobs:
  terraform:
    name: Apply Terraform VCN
    runs-on: ubuntu-latest

    env:
      OCI_TF_TENANCY_OCID: ${{ secrets.OCI_TF_TENANCY_OCID }}
      OCI_TF_USER_OCID: ${{ secrets.OCI_TF_USER_OCID }}
      OCI_TF_FINGERPRINT: ${{ secrets.OCI_TF_FINGERPRINT }}
      OCI_TF_PRIVATE_KEY: ${{ secrets.OCI_TF_PRIVATE_KEY }}
      OCI_TF_REGION: ${{ secrets.OCI_TF_REGION }}
      OCI_TF_COMPARTMENT_OCID: ${{ secrets.OCI_TF_COMPARTMENT_OCID }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Write private key to file
        run: |
          echo "${OCI_TF_PRIVATE_KEY}" > oci_api_key.pem
          chmod 600 oci_api_key.pem

      - name: Create terraform.tfvars
        run: |
          cat <<EOF > terraform.tfvars
          tenancy_ocid     = "${OCI_TF_TENANCY_OCID}"
          user_ocid        = "${OCI_TF_USER_OCID}"
          fingerprint      = "${OCI_TF_FINGERPRINT}"
          private_key_path = "./oci_api_key.pem"
          region           = "${OCI_TF_REGION}"
          compartment_ocid = "${OCI_TF_COMPARTMENT_OCID}"
          EOF

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve
